CREATE TABLE IF NOT EXISTS users
(
    id        SERIAL       NOT NULL UNIQUE PRIMARY KEY,
    user_name VARCHAR(255) NOT NULL,
    email     VARCHAR(255) NOT NULL,
    user_role VARCHAR(255) NOT NULL,
    password  VARCHAR(255) NOT NULL,
    birth_day TIMESTAMP WITHOUT TIME ZONE
)