server:
  port: 8081

spring:
  flyway:
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:54155/limemart
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:54155/limemart

jwt:
  secretKey: thisIsLocalSecretKeyForLimeMartWhickShouldBe256Bits?_